# This will be the first part of the title tag for your site <title> site.name + page.title </title>
title: V&A Travel
url: "https://vyaitravel.github.io/" # the base hostname & protocol for your site, e.g. http://example.com, also used in jekyll-seo-tag
baseurl:
repo: https://github.com/vyaitravel/vyaitravel.github.com
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
tagline:
description: Jekyll template for e-commerce with Gumroad integration
author:
  name: V&A Travel
  email:
  twitter: V&ATravel # twitter username without the @ symbol
  phone: ""
social:
  name: V&A Travel # replace this
  links:
    - https://github.com/vyaitravel/vyaitravel.github.com
    - https://www.facebook.com/vyai.pt

# Build settings
markdown: kramdown
timezone: FR

collections:
  products:
    _hide_content: false
    output: true

permalink: /:title/ # pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-leaflet
  - jekyll-feed
  - jekyll-archives # not on Supply theme

include:
  - .htaccess
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENCE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Contact settings
formcarry: https://formcarry.com/ # add you formcarry endpoint url (see https://formcarry.com/documentation/getting-started)

# Social

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

feed:
  collections:
    products:
      path: "/products.xml"

# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: 'all'
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'
  category_archive:
    type: liquid
